const language = en; //available languages: english (en), hungarian (hu), french (fr), portoguise (pt)
const numberOfPracticeBlocks = 0;
const numberOfBlocks = 20;
const numberOfBlockElements = 85;
const numberOfSequenceRepetitions = 10;
const patternTrialImage = "url(../static/images/dalmata.jpg)";
const randomTrialImage = "url(../static/images/dalmata.jpg)";
const secondTrialImage = "url(../static/images/penguin.jpg)";
const blockToBeginUsingSecondImage = 3;
const rsi = 120;
const initialDelay = 1000;